// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghbvslamotcpymkypoud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYnZzbGFtb3RjcHlta3lwb3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTE0NjYsImV4cCI6MjA3MjY2NzQ2Nn0.7RDvLwIIU6j2_JDVHR-QCIJm-r0NNKqQqKLM8Soudyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});